<a href="https://colab.research.google.com/github/sangramdhurve/Titanic_survival_prediction-all-Algorithms/blob/main/Titanic_survival.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#<------------------------------------------------------------**Data Dictionary**---------------------------------------------------->

---
Variable  | Definition                 | Key
--------------|----------------|----------------
survival      | Survival       | 0 = No, 1 = Yes
pclass        |Ticket class    | 1 = 1st, 2 = 2nd, 3 = 3rd
sex
Age	          |Age in years	
sibsp	        |#of siblings / spouses aboard the Titanic	
parch	        |#of parents / children aboard the Titanic	
ticket	      |Ticket number	
fare	        |Passenger fare	
cabin	        |Cabin number	
embarked	    |Port of Embarkation  |C = Cherbourg, Q = Queenstown, S = Southampton

---
---


#<------------------------------------------------------------ **Variable Notes** -------------------------------------------------->

**pclass**: A proxy for socio-economic status (SES)
1st = Upper
2nd = Middle
3rd = Lower

**age**: Age is fractional if less than 1. If the age is estimated, is it in the form of xx.5

**sibsp**: The dataset defines family relations in this way...
Sibling = brother, sister, stepbrother, stepsister
Spouse = husband, wife (mistresses and fiancés were ignored)

**parch**: The dataset defines family relations in this way...
Parent = mother, father
Child = daughter, son, stepdaughter, stepson
Some children travelled only with a nanny, therefore parch=0 for them.

#<---------------------------------------------**Import some important librarie** --------------------------------------->

In [124]:
import pandas as pd
import numpy as np

In [125]:
df = pd.read_csv("/content/drive/MyDrive/Python projects/Titanic/Titanic.csv")

In [126]:
df

PassengerId  Survived  Pclass  \
0            892         0       3   
1            893         1       3   
2            894         0       2   
3            895         0       3   
4            896         1       3   
..           ...       ...     ...   
413         1305         0       3   
414         1306         1       1   
415         1307         0       3   
416         1308         0       3   
417         1309         0       3   

                                             Name     Sex   Age  SibSp  Parch  \
0                                Kelly, Mr. James    male  34.5      0      0   
1                Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                       Myles, Mr. Thomas Francis    male  62.0      0      0   
3                                Wirz, Mr. Albert    male  27.0      0      0   
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   
..                                            ...     ...   ...    ...    ...   
413                            Spector, Mr. Woolf    male   NaN      0      0   
414                  Oliva y Ocana, Dona. Fermina  female  39.0      0      0   
415                  Saether, Mr. Simon Sivertsen    male  38.5      0      0   
416                           Ware, Mr. Frederick    male   NaN      0      0   
417                      Peter, Master. Michael J    male   NaN      1      1   

                 Ticket      Fare Cabin Embarked  
0                330911    7.8292   NaN        Q  
1                363272    7.0000   NaN        S  
2                240276    9.6875   NaN        Q  
3                315154    8.6625   NaN        S  
4               3101298   12.2875   NaN        S  
..                  ...       ...   ...      ...  
413           A.5. 3236    8.0500   NaN        S  
414            PC 17758  108.9000  C105        C  
415  SOTON/O.Q. 3101262    7.2500   NaN        S  
416              359309    8.0500   NaN        S  
417                2668   22.3583   NaN        C  

[418 rows x 12 columns]

#**<----------------------Preprocessing--------------------------->**

In [127]:
df['SibSp'].unique()

array([0, 1, 2, 3, 4, 5, 8])

In [128]:
df['Embarked'].unique()

array(['Q', 'S', 'C'], dtype=object)

In [129]:
df['Parch'].unique()

array([0, 1, 3, 2, 4, 6, 5, 9])

In [130]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [131]:
df.shape

(418, 12)

In [132]:
df1 = df.drop(['Cabin'], axis = 1)

In [133]:
df1.shape

(418, 11)

In [134]:
df1.isnull().sum()

PassengerId     0
Survived        0
Pclass          0
Name            0
Sex             0
Age            86
SibSp           0
Parch           0
Ticket          0
Fare            1
Embarked        0
dtype: int64

#Filling Null values using mean of the features

In [135]:
mean_value=df1['Age'].mean()
value1=df1['Fare'].mean()
df1['Age'].fillna(value=mean_value, inplace=True)
df1['Fare'].fillna(value=value1, inplace=True)

In [136]:
df1.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [137]:
count=0
for i in df1:
    print(i, end=', ')
    count+=1
print('\n Total no of counlmn in data set is =>', count)

PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Embarked, 
 Total no of counlmn in data set is => 11


In [138]:
df1.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   418.000000  418.000000  418.000000  418.000000  418.000000   
mean   1100.500000    0.363636    2.265550   30.272590    0.447368   
std     120.810458    0.481622    0.841838   12.634534    0.896760   
min     892.000000    0.000000    1.000000    0.170000    0.000000   
25%     996.250000    0.000000    1.000000   23.000000    0.000000   
50%    1100.500000    0.000000    3.000000   30.272590    0.000000   
75%    1204.750000    1.000000    3.000000   35.750000    1.000000   
max    1309.000000    1.000000    3.000000   76.000000    8.000000   

            Parch        Fare  
count  418.000000  418.000000  
mean     0.392344   35.627188  
std      0.981429   55.840500  
min      0.000000    0.000000  
25%      0.000000    7.895800  
50%      0.000000   14.454200  
75%      0.000000   31.500000  
max      9.000000  512.329200

#<-------------------split dataset in features and target variable-------------------->

In [139]:
feature_cols = ['PassengerId', 'Pclass', 'Age','SibSp',	'Parch',	'Fare'] 
X = df1[feature_cols].values # Features
y = df1.Survived # Target variable

In [140]:
y

0      0
1      1
2      0
3      0
4      1
      ..
413    0
414    1
415    0
416    0
417    0
Name: Survived, Length: 418, dtype: int64

#<------------------------- Split dataset into training set and test set-------------------------->

In [141]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

#<----------------------------------Feature Scaling-------------------------------->

In [142]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [143]:
X

array([[8.92000000e+02, 3.00000000e+00, 3.45000000e+01, 0.00000000e+00,
        0.00000000e+00, 7.82920000e+00],
       [8.93000000e+02, 3.00000000e+00, 4.70000000e+01, 1.00000000e+00,
        0.00000000e+00, 7.00000000e+00],
       [8.94000000e+02, 2.00000000e+00, 6.20000000e+01, 0.00000000e+00,
        0.00000000e+00, 9.68750000e+00],
       ...,
       [1.30700000e+03, 3.00000000e+00, 3.85000000e+01, 0.00000000e+00,
        0.00000000e+00, 7.25000000e+00],
       [1.30800000e+03, 3.00000000e+00, 3.02725904e+01, 0.00000000e+00,
        0.00000000e+00, 8.05000000e+00],
       [1.30900000e+03, 3.00000000e+00, 3.02725904e+01, 1.00000000e+00,
        1.00000000e+00, 2.23583000e+01]])

#<=======Using Logistic Regression Algorithm to the Training Set=====>

In [144]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(random_state = 0)
lr.fit(X_train, y_train)


LogisticRegression(random_state=0)

#Using KNeighborsClassifier Method of neighbors class to use Nearest Neighbor algorithm

In [145]:
from sklearn.neighbors import KNeighborsClassifier
kNN = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
kNN.fit(X_train, y_train)

KNeighborsClassifier()

#Using GaussianNB method of naïve_bayes class to use Naïve Bayes Algorithm

In [146]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)

GaussianNB()

#Using DecisionTreeClassifier of tree class to use Decision Tree Algorithm

In [147]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
dtc.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

#Using RandomForestClassifier method of ensemble class to use Random Forest Classification algorithm


In [148]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
rfc.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [149]:
y_pred = rfc.predict(X_test)

In [150]:
y_pred

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0])

#<--------------------------**Matrices**----------------------->

In [151]:
from sklearn.metrics import accuracy_score 
import sklearn.metrics as metrics
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Precision:",metrics.precision_score(y_test, y_pred))
print("Recall:",metrics.recall_score(y_test, y_pred))

Accuracy: 0.6547619047619048
Precision: 0.42105263157894735
Recall: 0.3076923076923077


#<---------------------------**Confusion_matrix**------------------------->

In [152]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[47, 11],
       [18,  8]])

#test the three models with the test data and print their **accuracy scores**


In [153]:
print('Logistic Regression Algorithm: {}'.format(lr.score(X_test, y_test)))
print('KNearest Neighbor algorithm: {}'.format(kNN.score(X_test, y_test)))
print('Naïve Bayes Algorithm: {}'.format(gnb.score(X_test, y_test)))
print(' Decision Tree Algorithm: {}'.format(dtc.score(X_test, y_test)))
print('Random Forest Classification: {}'.format(rfc.score(X_test, y_test)))

Logistic Regression Algorithm: 0.6666666666666666
KNearest Neighbor algorithm: 0.6666666666666666
Naïve Bayes Algorithm: 0.7023809523809523
 Decision Tree Algorithm: 0.5833333333333334
Random Forest Classification: 0.6547619047619048


#**<==========================The End===========================>**